Rip out the port cache
cloudandheat/ch-k8s-lbaas pull request #27
Opened 2022-05-11 10:00 UTC by horazont

2022-05-11 10:20 UTC, horazont commented
Test image available at `registry.gitlab.com/jssfr/stash/ch-k8s-lbaas-controller:feature-nocache`. I cannot upload builds here unfortunately, so you'll have to make them yourself.

2022-05-12 12:49 UTC, sebastianriese requested changes
Is there a chance to rename `cache.go` something like `ports.go` or would this cause problems?

2022-05-12 12:49 UTC, sebastianriese commented on internal/openstack/cache.go
> +					// TODO: warn here?!
If this isn't supposed to happen warning here would be good (as it may help with debugging).

2022-05-12 13:47 UTC, sebastianriese commented on internal/openstack/ports.go
> +  "k8s.io/klog"
Indentation is messed up here (seems to be tab vs. spaces) – go fmt to fix.

2022-05-16 05:41 UTC, closed without merging

2022-05-16 05:42 UTC, horazont commented
Merged as 8179501.

I did not see the comments, but I luckily ran go fmt in the meantime. And then I forgot to force push, so GitHub didn't see the merge correctly.